apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: zigbee2mqtt
    app.kubernetes.io/name: zigbee2mqtt
  name: zigbee2mqtt
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: web
  selector:
    app: zigbee2mqtt
  sessionAffinity: None
  type: ClusterIP
