apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 1
  labels:
    app.kubernetes.io/instance: zigbee2mqtt
    app.kubernetes.io/name: zigbee2mqtt
  name: zigbee2mqtt
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  serviceName: 'zigbee2mqtt'
  template:
    metadata:
      labels:
        app: zigbee2mqtt
        app.kubernetes.io/instance: zigbee2mqtt
        app.kubernetes.io/name: zigbee2mqtt
    spec:
      containers:
        - env:
            - name: TZ
              value: UTC
          image: koenkk/zigbee2mqtt:2.6.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: web
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: zigbee2mqtt
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 600Mi
            requests:
              cpu: 200m
              memory: 600Mi
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: zoneinfo
              mountPath: /etc/localtime
              subPath: America/New_York
              readOnly: true
#            - mountPath: /app/data/configuration.yaml
#              name: config-volume
#              subPath: configuration.yaml
            - mountPath: /app/data
              name: zigbee2mqtt-data
      volumes:
        - name: zoneinfo
          hostPath:
            path: /usr/share/zoneinfo
        - name: zigbee2mqtt-data
          hostPath:
            path: /home/tpearson/hass/zigbee2mqtt/k8s-data
#        - configMap:
#            defaultMode: 420
#            name: zigbee2mqtt
#          name: config-volume
        # We remove the explicit claimName reference here
#        - name: zigbee2mqtt-pvc
#          persistentVolumeClaim:
#            claimName: zigbee2mqtt-pvc  # This matches the claim template
#  volumeClaimTemplates:
#    - metadata:
#        name: zigbee2mqtt-pvc  # The name must match the volumeMounts name
#      spec:
#        accessModes: ["ReadWriteOnce"]
#        resources:
#          requests:
#            storage: 1Gi
